#!/usr/bin/env python
# coding: UTF-8

AddOption(
    '--debug-build',
    default=False)

env = Environment()

# build in debug mode ?
if GetOption('debug_build'):
  env.ParseFlags('-DDEBUG')
  env.Append(CCFLAGS=['-Wall','-g'])
else:
  env.Append(CCFLAGS=['-O3'])

env.Append(
    CCFLAGS=['-m32', '-ansi'],
    LINKFLAGS=['-m32'])

env.Program('um', ['um.c'])