#!/usr/bin/env python
# coding: UTF-8

AddOption(
    '--debug-build',
    action='store_true',
    help='debug build',
    default=False)

env = Environment()

# build in debug mode ?
if GetOption('debug_build'):
  env.ParseFlags('-DDEBUG')
  env.Append(CCFLAGS=['-Wall', '-g'])
else:
  env.Append(CCFLAGS=['-O3'])

env.Append(
    CPPPATH=['./v8/src'],
    LIBPATH=['./v8/out/ia32.debug/obj.target/tools/gyp'],
    LIBS=['v8_base', 'v8_snapshot'],
    CCFLAGS=['-m32'],
    LINKFLAGS=['-pthread', '-m32'])


env.Program('um', ['um.cpp'])
